FROM node:14 as build
WORKDIR /usr/local/app
COPY ./ /usr/local/app/
WORKDIR /usr/local/app/shared
RUN npm ci
RUN npm run build
WORKDIR /usr/local/app/frontend
RUN npm ci
RUN npm run build

FROM nginx:latest
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=build /usr/local/app/frontend/nginx.conf /etc/nginx/conf.d/beets.conf
COPY --from=build /usr/local/app/frontend/dist/frontend /usr/share/nginx/html
EXPOSE 80
